apiVersion: v1
kind: Service
metadata:
    name: miltoncamaraaspnetcorekubernetes_1
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: miltoncamaraaspnetcorekubernetes_1